### ISSUE TITLE
How to set typeface?

### ISSUE THREAD

**Issue by drunkendaddy** [RobertApikyan/SegmentedControl#1]
How do I change the font?

**Comment by RobertApikyan** [comment]
Hi, for font change, there is a new attribute in release 1.0.1

from XML use app:fontAssetPath="fonts/newFont.ttf"  and specify .ttf or .otf file path (in this case it's located in assets/fonts/newFont.ttf)
programmatically  segmentedControl.setTypeFace(typeface)

here is Gradle configs for release 1.0.1

In your app module build.gradle
dependencies {
	        compile 'com.github.RobertApikyan:SegmentedControl:release_1.0.1'
}

in application module build.gradle
  allprojects {
		repositories {
			maven { url 'https://jitpack.io' }
		}
	}
