### ISSUE TITLE
got error failed to resolve :com.android.support:appcompat-v7:27.1.1

### ISSUE THREAD

**Issue by Atepheh** [RobertApikyan/SegmentedControl#13]
when I add library to dependencies I got "failed to resolve :com.android.support:appcompat-v7:27.1.1" error.
my android compileSdkVersion is  25
buildToolsVersion is "25.0.3"

**Comment by RobertApikyan** [comment]
Do you add project level dependency ? 
allprojects { repositories { ... maven { url 'https://jitpack.io' } } }

**Comment by Atepheh** [comment]
Yes I did. This is my project level dependency:
allprojects {
    repositories {
        jcenter()
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.google.com/' }
    }
}

**Comment by RobertApikyan** [comment]
For now, the only solution for this, is to change target API version to last one (compileSdkVersion 28 buildToolsVersion '28.0.3'). I don't think there's any harm targeting API 28.
