### ISSUE TITLE
No selectedStrokeColor

### ISSUE THREAD

**Issue by CubanJaco** [RobertApikyan/SegmentedControl#15]
Hi Robert. Great work.

I have a small problem with segment control.

I have the following on XML
`<segmented_control.widget.custom.android.com.segmentedcontrol.SegmentedControl`
`android:id="@+id/segmented_control"`
            `android:layout_width="match_parent"`
            `android:layout_height="wrap_content"`
            `android:layout_below="@id/data_package"`
            `android:layout_margin="@dimen/small_margin"`
            `app:columnCount="3"`
            `app:distributeEvenly="true"`
            `app:radius="12dp"`
            `app:strokeWidth="2dp"`
            `app:focusedBackgroundColor="@color/pb_bg_color"`
            `app:selectedBackgroundColor="@color/pb_bg_color"`
            `app:selectedStrokeColor="@color/white"`
            `app:selectedTextColor="@color/white"`
            `app:textVerticalPadding="6dp"`
            `app:unSelectedStrokeColor="@color/white_disabled"`
            `app:unSelectedTextColor="@color/white_disabled" />`

and this from Kotlin:

`segmented_control.removeAllSegments()`
`val items = mutableListOf<String>()`
`(segmented_control as SegmentedControl<String>).addSegments(items)`

`segmented_control.setSelectedSegment(AppPreferences.lastPositionSegment)`
`if (!update) {`
`showDates(AppPreferences.lastPositionSegment)`
`}`

`segmented_control.addOnSegmentClickListener {`
`val position = it.absolutePosition`
`AppPreferences.lastPositionSegment = it.absolutePosition`
`showDates(position)`
`}`

But still getting a collorAccent stroke line when is selected a button, even when i defined on XML to use white color `app:selectedStrokeColor="@color/white"`

**Comment by RobertApikyan** [comment]
Hi, It's sims a bug, will be fixed in next release, but for now try to use instead of white color this one #fffffe

**Comment by CubanJaco** [comment]
Thanks Robert, it's working fine with #fffffe color, its curious because with #ffffff do not work.
Again, amazing job!
Thanks
