### ISSUE TITLE
selected or unselected attributes color issue

### ISSUE THREAD

**Issue by hivian** [RobertApikyan/SegmentedControl#18]
Hi,

Selected or unselected color attributes ((un)selectedStrokeColor, (un)selectedTextColor ... ) cannot be white. They accept any other colors, even a white color with alpha value, but it cannot be fully white (#ffffff).

**Comment by RobertApikyan** [comment]
Hi, the white color problem is now solved, here is the new version 
implementation 'com.github.RobertApikyan:SegmentedControl:1.1.3'
