### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by hivian** [RobertApikyan/SegmentedControl#20]
After updating the gradle wrapper to the latest version (gradle-5.1.1-all), I got these errors:

``error: cannot access SectionLayout
public final class SegmentViewHolder extends segmented_control.widget.custom.android.com.segmentedcontrol.item_row_column.SegmentViewHolder<java.lang.String> {
             ^
  class file for section_layout.widget.custom.android.com.sectionlayout.SectionLayout not found``

``e: java.lang.IllegalStateException: failed to analyze: java.lang.AssertionError: annotation tree hasn't been attributed yet: @kotlin.Metadata ...``

I'am using Kotlin.

**Comment by RobertApikyan** [comment]
Most probably, the new update will be available tomorrow

**Comment by RobertApikyan** [comment]
Hi, try this version implementation 'com.github.RobertApikyan:SegmentedControl:1.1.3' 
I'm closing this issue, but if something went wrong fill free to reopen it
