### ISSUE TITLE
How can make it multi select?

### ISSUE THREAD

**Issue by smae1993** [RobertApikyan/SegmentedControl#23]
How can i make this project multi selectable?

**Comment by wann2** [comment]
Me too. I'd also like to know how I can make it multi select.

**Comment by RobertApikyan** [comment]
it's a good idea, will add such a functionality most probably on this weekend

**Comment by wann2** [comment]
When can I please expect to use multi select function?

**Comment by RobertApikyan** [comment]
sorry for delay, will try to publish a new version till the end of day

**Comment by wann2** [comment]
Thanks for your kindness. Your library is very good!
It would be better if we could get the values of the items selected from the list.

**Comment by RobertApikyan** [comment]
Here is the new version of segmented control that supports multi selection.

implementation 'com.github.RobertApikyan:SegmentedControl:1.2-alpha'

For enabling multi selection use setSupportedSelectionsCount(int) programmatically and supportedSelectionsCount attribute from XML (default value is 1). it works in following way, if supportedSelectionCount = 3, then maximum 3 items can be in selected state at the same time, when the new item is selected the oldest selection become unselected.

For now it's in alpha release, please let me know if any problems will occur

**Comment by wann2** [comment]
Thank you very much. I think it will help a lot.

**Comment by wann2** [comment]
Hi, When I use "segmented_control.notifyConfigIsChanged();", the follow exception happens.
So I used try catch and no problem. This might help you to improve the source codes.

java.util.NoSuchElementException
at java.util.LinkedList.getLast(LinkedList.java:257)
W/System.err:     at segmented_control.widget.custom.android.com.segmentedcontrol.SegmentedControlControllerComponent.getLastSelectedViewHolder(SegmentedControlControllerComponent.java:103)
W/System.err:     at segmented_control.widget.custom.android.com.segmentedcontrol.SegmentedControlControllerComponent.recreate(SegmentedControlControllerComponent.java:201)
W/System.err:     at segmented_control.widget.custom.android.com.segmentedcontrol.SegmentedControlControllerComponent.notifyConfigIsChanged(SegmentedControlControllerComponent.java:156)
W/System.err:     at segmented_control.widget.custom.android.com.segmentedcontrol.SegmentedControl.notifyConfigIsChanged(SegmentedControl.java:620)

Many thanks.

**Comment by RobertApikyan** [comment]
Hi, thanks for reporting the issue, now it's fixed, 
here is the new version's dependency 
implementation 'com.github.RobertApikyan:SegmentedControl:1.2.0.1-alpha'

**Comment by RobertApikyan** [comment]
Hi, I am closing the issue, if any problem will occur please fill free to reopen it
