### ISSUE TITLE
supporting RTL

### ISSUE THREAD

**Issue by alahammad** [RobertApikyan/SegmentedControl#6]
Hello,

I would like to thank you for great library, I have question if any planning to support RTL in future ..

Thanks,

**Comment by RobertApikyan** [comment]
Hi, thank you for positive review, I'v never thought about RTL for segmented control .. However It will be added in upcoming release (in the end of september).

**Comment by alahammad** [comment]
for who facing this issue, as workaround you set android:layoutDirection="ltr" for you segment controller then segment will not effect with RTL.
